AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AppPort:
    Type: String
    Default: '8080'

Resources:

  MacPrivateNlbTg:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckProtocol: 'TCP'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: MacPrivateNlbTg
      Port: !Ref AppPort
      Protocol: TCP
      TargetType: ip
      VpcId: !ImportValue MacVpc

  MacPrivateNlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref MacPrivateNlbTg
          Type: forward
      LoadBalancerArn: !Ref MacPrivateNlb
      Port: 80
      Protocol: TCP

  MacPrivateNlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MacPrivateNlb
      Scheme: internal
      Type: network
      Subnets:
        - !ImportValue MacPrivateSubnet1
        - !ImportValue MacPrivateSubnet2
