AWSTemplateFormatVersion: '2010-09-09'
Description: A sample of setting up EC2 with public VPC

Parameters:
  MacVpcId:
    Type: String
  MacPublicSubnetId:
    Type: String

Resources:

  MacSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: "Sample Sg"
        VpcId: !Ref MacVpcId
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      
  MacEc2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.nano
      ImageId: ami-0c20b8b385217763f
      KeyName: mac-ec2-kp
      NetworkInterfaces: 
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet: 
            - !Ref MacSg
          SubnetId: !Ref MacPublicSubnetId
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          cd /home/ubuntu
          echo "hello" >> index.html
          python3 -m http.server 80
