AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcId:
    Type: String
  SubnetId1:
    Type: String
  SubnetId2:
    Type: String

Resources:
  MacDb:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 12.5
      DBInstanceClass: db.t2.medium
      DBInstanceIdentifier: macdb
      DBName: macdb
      MasterUsername: mackittipat
      MasterUserPassword: password
      AllocatedStorage: 5
      VPCSecurityGroups:
        - !Ref MacDbSecurityGroup
      DBSubnetGroupName: !Ref MacDbSubnetGroup
      MultiAZ: true
      PubliclyAccessible: true

  MacDbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MacDbSecurityGroup
      GroupDescription: Security group for DB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  MacDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MacDbSubnetGroup
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2
